title: Speak For Me
email: info@speakforme.in
description: >
  Speak for Me
baseurl: ""
url: "https://speakforme.in"
twitter_username: speakforme
github_username:  speakforme
thumbnail: /public/thumbnail.png
# Build settings
markdown: kramdown
google_analytics: UA-82421266-2
exclude:
  - _locales
  - _scripts
  - src
  - config
  - scripts
  - package.json
  - package-lock.json
  - HACKING.md
  - Gulpfile.js
  - Gemfile.lock
  - Gemfile
  - CNAME
# https://www.netlify.com/docs/redirects/
include:
  - _redirects
  - _headers
collections:
  petitions:
    output: true
